theme: jekyll-theme-minimal
title: Hassan Shah Portfolio
plugins:
  - jekyll-feed
  - jekyll-seo-tag
logo: /images/photo.png
description: Solving problems and driving insights in Finance, Healthcare, Education, Budgets, etc. with Data. For collaboration or inquiries, contact me at hassanhshah@gmail.com
